"""Text and URL canonicalization for the duplicate and rule checks.

``normalize_text``, ``canonical_url``, ``sha256`` and ``extract_key_numbers``
run in C++ (``premarket_fastpath``) when it's installed. The ``ref_*``
functions below are the pure-Python reference: they define the behavior,
and the parity tests check the C++ module against them on random input.

Everything works on already-decoded ``str``. The C++ side sees the same text
as UTF-8 bytes and only ever changes ASCII bytes (or removes the listed
zero-width characters), so the two agree byte for byte.
"""

from __future__ import annotations

import hashlib
import re
import string
import unicodedata

from ai_api.dedup import fastpath

_ASCII_SPACE = " \t\n\r\f\v"
_ASCII_LOWER = str.maketrans(string.ascii_uppercase, string.ascii_lowercase)
_ASCII_ALNUM = frozenset(string.ascii_letters + string.digits)
# Soft hyphen and zero-width characters: invisible, so they're dropped.
_INVISIBLE = frozenset("\u00ad\u200b\u200c\u200d\u2060\ufeff")
_ENTITIES = (
    ("&amp;", "&"),
    ("&lt;", "<"),
    ("&gt;", ">"),
    ("&quot;", '"'),
    ("&#39;", "'"),
    ("&apos;", "'"),
    ("&nbsp;", " "),
)
# "<" starts a tag only when one of these follows it ("x < 5" stays).
_TAG_START = frozenset(string.ascii_letters + "/!?")
_SCHEME = re.compile(r"[A-Za-z][A-Za-z0-9+.\-]*\Z")
_TRACKING_KEYS = frozenset(
    {"ref", "ref_src", "fbclid", "gclid", "igshid", "mc_cid", "mc_eid"}
)
_DEFAULT_PORTS = frozenset({("http", "80"), ("https", "443")})
# ASCII digits only: re's \d would also match other scripts' digits.
_NUMBER = re.compile(r"\$?[0-9][0-9,]*(?:\.[0-9]+)?%?")
# Words that carry facts: "two" vs "three" companies, "March" vs "June".
_MONTH_WORDS = (
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
)
_NUMBER_WORDS = (
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
)
_FACT_WORDS = frozenset(_MONTH_WORDS + _NUMBER_WORDS)

# Vendor boilerplate, removed before any check: the synthetic marker, the
# newswire dateline ("NEW YORK, September 24 (Acme Market Wire) --") and
# the synthetic footer. The rules must not see the simulation's labels.
_SYNTHETIC_PREFIX = re.compile(r"\A\s*\[SYNTHETIC\]\s*", re.IGNORECASE)
# Any whitespace between the parts: copies re-space the text.
_DATELINE = re.compile(
    r"\A\s*[A-Z][A-Za-z .'\-]{0,40},\s+[A-Z][a-z]{2,9}\.?\s+[0-9]{1,2}"
    r"\s+\([^()\n]{1,60}\)\s+--\s*"
)
_FOOTER = "Generated by premarket-ai vendor-sim. Not real news."


def _ascii_lower(text: str) -> str:
    return text.translate(_ASCII_LOWER)


def ref_normalize_text(text: str) -> str:
    """Reference of the C++ ``normalize_text`` (the text after NFKC).

    In one left-to-right pass: HTML tags become a space, a few entities are
    decoded (``&amp; &lt; &gt; &quot; &#39; &apos; &nbsp;``; the result is
    never parsed again), invisible characters are dropped, ASCII letters are
    lowercased, and runs of ASCII whitespace become one space, trimmed. A
    tag is ``<`` followed by a letter, ``/``, ``!`` or ``?``, up to the next
    ``>``; without a ``>`` it's plain text. Numbers are kept.

    Args:
        text: Any text.

    Returns:
        The normalized text.
    """
    out: list[str] = []
    pending_space = False

    def emit(char: str) -> None:
        nonlocal pending_space
        if char in _ASCII_SPACE:
            pending_space = bool(out)
        elif char not in _INVISIBLE:
            if pending_space:
                out.append(" ")
                pending_space = False
            out.append(_ascii_lower(char))

    i = 0
    length = len(text)
    while i < length:
        char = text[i]
        if char == "<" and i + 1 < length and text[i + 1] in _TAG_START:
            end = text.find(">", i + 1)
            if end != -1:
                emit(" ")
                i = end + 1
                continue
        if char == "&":
            for entity, replacement in _ENTITIES:
                if text.startswith(entity, i):
                    emit(replacement)
                    i += len(entity)
                    break
            else:
                emit(char)
                i += 1
            continue
        emit(char)
        i += 1
    return "".join(out)


def _split_host_port(hostport: str) -> tuple[str, str | None]:
    """Splits ``host[:port]``; IPv6 hosts keep their brackets."""
    if hostport.startswith("["):
        end = hostport.find("]")
        if end != -1:
            rest = hostport[end + 1 :]
            if rest.startswith(":"):
                return hostport[: end + 1], rest[1:]
            return hostport, None
    host, colon, port = hostport.rpartition(":")
    if not colon:
        return hostport, None
    return host, port


def _is_tracking(param: str) -> bool:
    key = _ascii_lower(param.partition("=")[0])
    return key.startswith("utm_") or key in _TRACKING_KEYS


def ref_canonical_url(url: str) -> str:
    """Reference of the C++ ``canonical_url``: the L0 duplicate key.

    Lowercases the scheme and host, drops a default port (``http:80``,
    ``https:443``) or an empty one, the fragment, trailing slashes of the
    path, and tracking parameters (``utm_*``, ``ref``, ``ref_src``,
    ``fbclid``, ``gclid``, ``igshid``, ``mc_cid``, ``mc_eid``; keys compared
    in ASCII lowercase), then sorts the remaining query parameters. The
    user info, path and parameter values keep their case.

    Args:
        url: An absolute URL such as ``https://a.example/x?utm_source=y``.

    Returns:
        The canonical URL.

    Raises:
        ValueError: ``url`` has no valid ``scheme://`` or no host.
    """
    text = url.strip(_ASCII_SPACE)
    scheme, separator, rest = text.partition("://")
    if not separator or not _SCHEME.match(scheme):
        raise ValueError(f"not an absolute URL: {url!r}")
    scheme = _ascii_lower(scheme)
    rest = rest.partition("#")[0]
    cut = len(rest)
    for mark in "/?":
        position = rest.find(mark)
        if position != -1:
            cut = min(cut, position)
    authority, tail = rest[:cut], rest[cut:]
    userinfo, at, hostport = authority.rpartition("@")
    host, port = _split_host_port(hostport)
    host = _ascii_lower(host)
    if not host:
        raise ValueError(f"URL has no host: {url!r}")
    if port is not None and (port == "" or (scheme, port) in _DEFAULT_PORTS):
        port = None
    canonical = f"{scheme}://"
    if at:
        canonical += f"{userinfo}@"
    canonical += host
    if port is not None:
        canonical += f":{port}"
    path, _, query = tail.partition("?")
    canonical += path.rstrip("/")
    params = sorted(
        param for param in query.split("&") if param and not _is_tracking(param)
    )
    if params:
        canonical += "?" + "&".join(params)
    return canonical


def ref_sha256(text: str) -> str:
    """Reference of the C++ ``sha256``: lowercase hex SHA-256 of UTF-8."""
    return hashlib.sha256(text.encode()).hexdigest()


def _strip_non_alnum(token: str) -> str:
    start = 0
    end = len(token)
    while start < end and token[start] not in _ASCII_ALNUM:
        start += 1
    while end > start and token[end - 1] not in _ASCII_ALNUM:
        end -= 1
    return token[start:end]


def ref_extract_key_numbers(text: str) -> list[str]:
    """Reference of the C++ ``extract_key_numbers``: the facts of a story.

    Two stories that differ in one of these are different stories ("profit
    up 5%" vs "up 50%"), however similar their words are.

    Args:
        text: Normalized text (``normalize_text``).

    Returns:
        Sorted, unique: every number as written (``$`` and ``%`` kept,
        thousands commas removed; ``$85.1B`` gives ``$85.1``), plus month
        names and the number words zero to twelve (tokens split on spaces,
        with leading and trailing non-alphanumeric characters removed).
    """
    facts = {match.group().replace(",", "") for match in _NUMBER.finditer(text)}
    for token in text.split(" "):
        word = _strip_non_alnum(token)
        if word in _FACT_WORDS:
            facts.add(word)
    return sorted(facts)


def normalize_text(text: str) -> str:
    """Unicode NFKC, then ``ref_normalize_text`` (in C++ when available)."""
    nfkc = unicodedata.normalize("NFKC", text)
    native = fastpath.module()
    if native is None:
        return ref_normalize_text(nfkc)
    return native.normalize_text(nfkc)


def canonical_url(url: str) -> str:
    """See ``ref_canonical_url`` (in C++ when available).

    Raises:
        ValueError: The URL isn't absolute or has no host.
    """
    native = fastpath.module()
    if native is None:
        return ref_canonical_url(url)
    return native.canonical_url(url)


def sha256(text: str) -> str:
    """Lowercase hex SHA-256 of the UTF-8 text (in C++ when available)."""
    native = fastpath.module()
    if native is None:
        return ref_sha256(text)
    return native.sha256(text)


def extract_key_numbers(text: str) -> list[str]:
    """See ``ref_extract_key_numbers`` (in C++ when available)."""
    native = fastpath.module()
    if native is None:
        return ref_extract_key_numbers(text)
    return native.extract_key_numbers(text)


def strip_boilerplate(headline: str, body: str) -> tuple[str, str]:
    """Removes the vendor's marker, dateline and synthetic footer.

    Args:
        headline: The vendor headline.
        body: The vendor body.

    Returns:
        The headline and body the checks see.
    """
    headline = _SYNTHETIC_PREFIX.sub("", headline, count=1)
    body = body.replace(_FOOTER, "")
    body = _DATELINE.sub("", body, count=1)
    return headline.strip(), body.strip()


def dedup_text(headline: str, body: str) -> str:
    """The normalized story (headline, newline, body) without boilerplate."""
    headline, body = strip_boilerplate(headline, body)
    return normalize_text(f"{headline}\n{body}")
