"""Dedup L3: paraphrases, conflicting versions, order and window."""

import asyncio
import datetime

from ai_api.dedup import config
from ai_api.dedup import paraphrase
from ai_api.dedup import service

_DAY = datetime.date(2026, 9, 24)
_ORIGINAL = (
    "Apple reports Q3 revenue of $85.1B, up 12% from a year ago",
    "NEW YORK, September 24 (Acme Market Wire) -- Apple Inc. (AAPL) said "
    "revenue for its fiscal Q3 reached $85.1 billion, up 12% from a year "
    "earlier. Earnings per share were $1.40. Management will discuss the "
    "results on its scheduled conference call.",
)
_PARAPHRASE = (
    "Apple quarterly sales climb 12% to $85.1 billion",
    "NEW YORK, September 24 (Acme Market Wire) -- Sales at Apple Inc. (AAPL) "
    "rose 12% year over year to $85.1 billion in fiscal Q3, the company said. "
    "It reported earnings of $1.40 per share and will hold its usual call "
    "with analysts.",
)
_OTHER_NUMBERS = (
    _ORIGINAL[0].replace("12%", "20%"),
    _ORIGINAL[1].replace("12%", "20%"),
)


def _item(news_id, number, text, day=_DAY, tickers=("AAPL",)):
    return service.DedupItem(
        news_id=news_id,
        feed_date=day,
        vendor_item_id=f"VND-{day:%Y%m%d}-{number:03d}",
        headline=text[0],
        body=text[1],
        source_url=f"https://wire.example/{news_id}",
        tickers=tickers,
    )


def _check(items_and_vectors, **settings):
    index = paraphrase.MemoryVectorIndex()
    check = paraphrase.ParaphraseCheck(index, config.DedupConfig(**settings))

    async def run():
        return [
            await check.check(paraphrase.VectorEntry.of(item, vector))
            for item, vector in items_and_vectors
        ]

    return asyncio.run(run()), index


def test_paraphrase_is_linked_to_the_original():
    results, index = _check(
        [
            (_item(1, 1, _ORIGINAL), [1.0, 0.0, 0.0]),
            (_item(2, 2, _PARAPHRASE), [0.96, 0.28, 0.0]),
        ]
    )
    assert results[0] == (None, None)
    match, conflict = results[1]
    assert conflict is None
    assert (match.dup_type, match.level, match.canonical_id) == (
        "paraphrase",
        "L3",
        1,
    )
    assert match.score == 0.96
    assert match.word_edits >= 10
    assert not match.stale
    assert len(index) == 1


def test_other_numbers_make_a_conflicting_version_not_a_copy():
    results, index = _check(
        [
            (_item(1, 1, _ORIGINAL), [1.0, 0.0, 0.0]),
            (_item(2, 2, _OTHER_NUMBERS), [0.99, 0.1, 0.0]),
        ]
    )
    match, conflict = results[1]
    assert match is None
    assert conflict.canonical_id == 1
    assert "12%" in conflict.detail and "20%" in conflict.detail
    assert len(index) == 2


def test_other_tickers_are_a_different_story():
    results, _ = _check(
        [
            (_item(1, 1, _ORIGINAL), [1.0, 0.0, 0.0]),
            (_item(2, 2, _PARAPHRASE, tickers=("MSFT",)), [1.0, 0.0, 0.0]),
        ]
    )
    assert results[1] == (None, None)


def test_low_similarity_is_unique():
    results, _ = _check(
        [
            (_item(1, 1, _ORIGINAL), [1.0, 0.0, 0.0]),
            (_item(2, 2, _PARAPHRASE), [0.5, 0.86, 0.0]),
        ]
    )
    assert results[1] == (None, None)


def test_an_earlier_day_is_stale_and_the_window_is_respected():
    earlier = _DAY - datetime.timedelta(days=2)
    pairs = [
        (_item(1, 1, _ORIGINAL, day=earlier), [1.0, 0.0, 0.0]),
        (_item(2, 2, _PARAPHRASE), [0.97, 0.2, 0.0]),
    ]
    results, _ = _check(pairs)
    assert results[1][0].stale
    results, _ = _check(pairs, window_days=1)
    assert results[1] == (None, None)


def test_a_later_item_never_becomes_the_original():
    results, _ = _check(
        [
            (_item(2, 2, _PARAPHRASE), [1.0, 0.0, 0.0]),
            (_item(1, 1, _ORIGINAL), [0.97, 0.2, 0.0]),
        ]
    )
    # Checked out of order: item 1 comes first in the vendor's sequence.
    assert results[1] == (None, None)


def test_embed_text_drops_the_boilerplate():
    text = paraphrase.embed_text(
        "[SYNTHETIC] Apple  reports",
        "NEW YORK, September 24 (Acme Market Wire) -- Apple said.\n\n"
        "Generated by premarket-ai vendor-sim. Not real news.",
    )
    assert text == "Apple reports Apple said."
