"""Text and URL canonicalization (the behavior both backends share)."""

import pytest

from ai_api.dedup import normalize


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("  Hello\t\nWORLD  ", "hello world"),
        ("<p>Profit <b>up</b></p> 5%", "profit up 5%"),
        ("x < 5 and y>3", "x < 5 and y>3"),
        ("<unclosed tag", "<unclosed tag"),
        ("AT&amp;T &lt;b&gt; &nbsp;x", "at&t <b> x"),
        ("&unknown; &", "&unknown; &"),
        ("zero\u200bwidth\ufeff soft\u00adhyphen", "zerowidth softhyphen"),
        ("ÉCOLE Ärger", "École Ärger"),
        ("", ""),
    ],
)
def test_ref_normalize_text(text, expected):
    assert normalize.ref_normalize_text(text) == expected


def test_normalize_text_applies_nfkc_first():
    # Full-width letters and a no-break space become ASCII first.
    wide = "\uff2e\uff36\uff29\uff24\uff29\uff21\u00a0Q3"
    assert normalize.normalize_text(wide) == "nvidia q3"


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        (
            "HTTPS://Wire.VendorNews.EXAMPLE/2026/09/24/Story-001/"
            "?utm_source=vendorfeed&utm_medium=api#top",
            "https://wire.vendornews.example/2026/09/24/Story-001",
        ),
        ("http://a.example:80/x?b=2&a=1", "http://a.example/x?a=1&b=2"),
        ("https://a.example:443", "https://a.example"),
        ("https://a.example:8443/", "https://a.example:8443"),
        ("https://a.example:/x", "https://a.example/x"),
        (
            "https://User@A.example/x?REF=1&keep=Yes",
            "https://User@a.example/x?keep=Yes",
        ),
        ("https://[::1]:443/x", "https://[::1]/x"),
        ("  https://a.example/x?fbclid=1&gclid=2  ", "https://a.example/x"),
    ],
)
def test_canonical_url(url, expected):
    assert normalize.canonical_url(url) == expected
    assert normalize.ref_canonical_url(url) == expected


@pytest.mark.parametrize(
    "url",
    ["", "a.example/x", "://a.example", "1http://x", "https://", "https:///x"],
)
def test_canonical_url_rejects_non_absolute_urls(url):
    with pytest.raises(ValueError):
        normalize.canonical_url(url)


def test_extract_key_numbers():
    text = (
        "apple reports q3 revenue of $85.1b, up 12% from $1,234.50; "
        "board meets march 3, 2026 and splits into two"
    )
    assert normalize.extract_key_numbers(text) == [
        "$1234.50",
        "$85.1",
        "12%",
        "2026",
        "3",
        "march",
        "two",
    ]
    assert normalize.extract_key_numbers("profit up 5%") != (
        normalize.extract_key_numbers("profit up 50%")
    )
    assert normalize.extract_key_numbers("$ and % alone") == []


def test_sha256():
    assert normalize.sha256("abc") == (
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    )


def test_strip_boilerplate_removes_marker_dateline_and_footer():
    headline, body = normalize.strip_boilerplate(
        "[SYNTHETIC] Apple raises dividend",
        "NEW YORK, September 24 (Acme Market Wire) -- Apple Inc. (AAPL) "
        "raised it.\n\nGenerated by premarket-ai vendor-sim. Not real news.",
    )
    assert headline == "Apple raises dividend"
    assert body == "Apple Inc. (AAPL) raised it."


def test_dedup_text_ignores_the_day_and_formatting():
    one = normalize.dedup_text(
        "[SYNTHETIC] Apple raises dividend",
        "NEW YORK, September 24 (Acme Market Wire) -- Apple raised it.",
    )
    two = normalize.dedup_text(
        "[SYNTHETIC] APPLE  RAISES DIVIDEND",
        "NEW YORK, September 21 (Acme Market Wire) --   Apple raised it.",
    )
    assert one == two == "apple raises dividend apple raised it."
