"""DedupService against a fake Redis: levels, order, window, guard, rebuild."""

import asyncio
import datetime

import fakeredis

from ai_api.dedup import config
from ai_api.dedup import service
from ai_api.dedup import store

_DAY = datetime.date(2026, 9, 24)
_BODY = (
    "NEW YORK, September 24 (Acme Market Wire) -- Apple Inc. (AAPL) said "
    "revenue for its fiscal Q3 reached $85.1 billion, up 12% from a year "
    "earlier. Earnings per share were $1.40. Management will discuss the "
    "results on its scheduled conference call.\n\nGenerated by premarket-ai "
    "vendor-sim. Not real news."
)
_HEADLINE = "[SYNTHETIC] Apple reports Q3 revenue of $85.1B, up 12%"
_URL = "https://wire.vendornews.example/2026/09/24/apple-001"


def _item(news_id, number, day=_DAY, **overrides):
    fields = {
        "news_id": news_id,
        "feed_date": day,
        "vendor_item_id": f"VND-{day:%Y%m%d}-{number:03d}",
        "headline": _HEADLINE,
        "body": _BODY,
        "source_url": f"{_URL}-{news_id}",
        "tickers": ("AAPL",),
    }
    fields.update(overrides)
    return service.DedupItem(**fields)


def _service(redis=None, **settings):
    cfg = config.DedupConfig(**settings)
    if redis is None:
        redis = fakeredis.FakeAsyncRedis(decode_responses=True)
    return service.DedupService(store.DedupStore(redis, cfg.ttl_s), cfg), redis


def _run(items, dedup=None):
    if dedup is None:
        dedup, _ = _service()
    return asyncio.run(dedup.check_batch(items))


def test_exact_copy_is_l1_even_with_different_case_and_spacing():
    copy = _item(
        2, 2, headline=_HEADLINE.upper(), body=_BODY.replace(" ", "  ", 3)
    )
    first, second = _run([_item(1, 1), copy])
    assert first is None
    assert (second.dup_type, second.level, second.canonical_id) == (
        "exact",
        "L1",
        1,
    )
    assert second.stale is False


def test_same_url_with_tracking_params_is_l0():
    copy = _item(
        2,
        2,
        body=_BODY.replace("said", "stated and said"),
        source_url=f"{_URL}-1?utm_source=vendorfeed&utm_medium=api",
    )
    _, match = _run([_item(1, 1), copy])
    assert (match.dup_type, match.level) == ("url", "L0")


def test_one_word_edit_is_a_near_duplicate():
    copy = _item(2, 2, body=_BODY.replace(" said ", " stated ", 1))
    _, match = _run([_item(1, 1), copy])
    assert (match.dup_type, match.level) == ("near", "L2")
    assert match.word_edits == 2
    assert match.score <= 10


def test_a_different_number_is_a_different_story():
    """The guard: "up 12%" vs "up 120%" must never be hidden as a copy."""
    other = _item(2, 2, body=_BODY.replace("up 12%", "up 120%"))
    assert _run([_item(1, 1), other]) == [None, None]


def test_a_different_ticker_is_a_different_story():
    other = _item(2, 2, tickers=("MSFT",), body=_BODY.replace(" said ", " "))
    assert _run([_item(1, 1), other]) == [None, None]


def test_many_word_changes_are_not_near():
    other = _item(
        2,
        2,
        body=_BODY.replace(
            "Management will discuss the results",
            "Executives are expected to walk analysts through the figures",
        ),
    )
    assert _run([_item(1, 1), other]) == [None, None]


def test_a_copy_from_an_earlier_day_is_stale():
    earlier = _DAY - datetime.timedelta(days=3)
    dedup, _ = _service()
    old = _item(1, 7, day=earlier)
    today = _item(9, 1)
    assert _run([old, today], dedup) == [
        None,
        service.DedupMatch(
            1, "VND-20260921-007", earlier, "exact", "L1", stale=True
        ),
    ]


def test_copies_older_than_the_window_are_new_again():
    earlier = _DAY - datetime.timedelta(days=8)
    assert _run([_item(1, 1, day=earlier), _item(2, 1)]) == [None, None]


def test_checking_again_gives_the_same_answer():
    dedup, _ = _service()
    items = [_item(1, 1), _item(2, 2, headline=_HEADLINE.upper())]
    first = _run(items, dedup)
    assert _run(items, dedup) == first
    assert first[0] is None
    assert first[1].canonical_id == 1


def test_an_earlier_item_checked_later_is_not_a_copy_of_a_later_one():
    dedup, _ = _service()
    _run([_item(2, 5)], dedup)
    # VND-...-001 comes before -005 in the vendor's sequence.
    assert _run([_item(1, 1)], dedup) == [None]


def test_rebuilding_the_index_restores_matches():
    dedup, _ = _service()
    asyncio.run(dedup.index_unique([_item(1, 1)]))
    asyncio.run(dedup.mark_day(_DAY))
    assert asyncio.run(dedup.has_day(_DAY))
    _, match = _run([_item(1, 1), _item(2, 2)], dedup)
    assert match.canonical_id == 1


def test_word_edits_count_both_sides_and_ignore_order():
    assert service.word_edits("a b c", "c b a") == 0
    assert service.word_edits("up 5%", "higher by 5%") == 3
    assert service.word_edits("a a b", "a b") == 1


def test_config_from_env_and_band_count():
    cfg = config.DedupConfig.from_env(
        {"DEDUP_SIMHASH_MAX_HAMMING": "7", "DEDUP_WINDOW_DAYS": "3"}
    )
    assert (cfg.bands, cfg.window_days, cfg.ttl_s) == (8, 3, 4 * 86_400)
    for env in (
        {"DEDUP_SIMHASH_MAX_HAMMING": "64"},
        {"DEDUP_WINDOW_DAYS": "x"},
    ):
        try:
            config.DedupConfig.from_env(env)
        except ValueError:
            continue
        raise AssertionError(env)
