"""C++20 fast path of the ai-api duplicate and rule checks."""

def normalize_text(text: str) -> str: ...
def canonical_url(url: str) -> str: ...
def sha256(text: str) -> str: ...
def extract_key_numbers(text: str) -> list[str]: ...
def simhash64(text: str, ngram: int = 2) -> int: ...
def hamming(a: int, b: int) -> int: ...
def band_keys(value: int, bands: int) -> list[int]: ...
