// Copyright 2026 premarket-ai contributors
// SPDX-License-Identifier: MIT

#include "ingest/feed_parser.h"

#include <string>
#include <vector>

#include "gtest/gtest.h"

namespace premarket {
namespace legacy {
namespace {

const char kItem[] =
    "{\"id\":\"VND-20260924-001\",\"headline\":\"[SYNTHETIC] Apple beats\","
    "\"body\":\"Line one.\\n\\nGenerated by premarket-ai vendor-sim.\","
    "\"source_url\":\"https://wire.vendornews.example/a\","
    "\"source_domain\":\"wire.vendornews.example\","
    "\"published_at\":\"2026-09-24T09:05:00Z\","
    "\"tickers\":[\"AAPL\",\"MSFT\"],\"synthetic\":true}";

TEST(ParseItemTest, ParsesEveryField) {
  StatusOr<NewsItem> item = ParseItem(kItem);
  ASSERT_TRUE(item.ok()) << item.status().ToString();
  EXPECT_EQ(item.value().vendor_item_id, "VND-20260924-001");
  EXPECT_EQ(item.value().headline, "[SYNTHETIC] Apple beats");
  EXPECT_EQ(item.value().body,
            "Line one.\n\nGenerated by premarket-ai vendor-sim.");
  EXPECT_EQ(item.value().source_domain, "wire.vendornews.example");
  EXPECT_EQ(item.value().published_at, "2026-09-24T09:05:00Z");
  ASSERT_EQ(item.value().tickers.size(), 2u);
  EXPECT_EQ(item.value().tickers[1], "MSFT");
  EXPECT_TRUE(item.value().synthetic);
  EXPECT_FALSE(item.value().is_dup);
}

TEST(ParseItemTest, RejectsMissingField) {
  StatusOr<NewsItem> item = ParseItem(
      "{\"id\":\"x\",\"headline\":\"h\",\"source_url\":\"u\","
      "\"source_domain\":\"d\",\"published_at\":\"p\",\"tickers\":[]}");
  ASSERT_FALSE(item.ok());
  EXPECT_NE(item.status().message().find("body"), std::string::npos);
}

TEST(ParseItemTest, RejectsWrongTypes) {
  EXPECT_FALSE(ParseItem("{\"id\":1}").ok());
  EXPECT_FALSE(ParseItem("[1,2]").ok());
  EXPECT_FALSE(ParseItem("not json").ok());
  std::string bad_ticker = kItem;
  bad_ticker.replace(bad_ticker.find("\"MSFT\""), 6, "42");
  EXPECT_FALSE(ParseItem(bad_ticker).ok());
}

TEST(SplitFeedTest, SplitsItemsInOrder) {
  const std::string feed =
      std::string("{\"feed_date\":\"2026-09-24\",\"items\":[") + kItem + "," +
      kItem + "]}";
  StatusOr<std::vector<std::string>> items = SplitFeed(feed);
  ASSERT_TRUE(items.ok()) << items.status().ToString();
  ASSERT_EQ(items.value().size(), 2u);
  StatusOr<NewsItem> first = ParseItem(items.value()[0]);
  ASSERT_TRUE(first.ok());
  EXPECT_EQ(first.value().headline, "[SYNTHETIC] Apple beats");
}

TEST(SplitFeedTest, RejectsBadFeeds) {
  EXPECT_FALSE(SplitFeed("").ok());
  EXPECT_FALSE(SplitFeed("{\"items\":{}}").ok());
  EXPECT_FALSE(SplitFeed("{\"count\":0}").ok());
  EXPECT_TRUE(SplitFeed("{\"items\":[]}").ok());
}

}  // namespace
}  // namespace legacy
}  // namespace premarket
