// Copyright 2026 premarket-ai contributors
// SPDX-License-Identifier: MIT

#include "ingest/content_hash.h"

#include <array>
#include <memory>
#include <string>
#include <string_view>

#include "absl/status/statusor.h"
#include "gtest/gtest.h"
#include "ingest/news_item.h"

namespace premarket::ingest {
namespace {

// The same vectors as cpp/legacy/tests/normalize_test.cc.
TEST(NormalizeTextTest, LowercasesAndCollapsesWhitespace) {
  EXPECT_EQ(NormalizeText("  Apple   REPORTS\tQ3\n\nRevenue  "),
            "apple reports q3 revenue");
}

TEST(NormalizeTextTest, KeepsNumbersAndPunctuation) {
  EXPECT_EQ(NormalizeText("Profit up 5%"), "profit up 5%");
  EXPECT_NE(NormalizeText("Profit up 5%"), NormalizeText("Profit up 50%"));
}

TEST(NormalizeTextTest, EmptyAndBlank) {
  EXPECT_EQ(NormalizeText(""), "");
  EXPECT_EQ(NormalizeText(" \t\n "), "");
}

TEST(NormalizeTextTest, FormFeedAndVerticalTabAreSpace) {
  EXPECT_EQ(NormalizeText("a\fb\vC"), "a b c");
}

TEST(Sha256HexTest, KnownVectors) {
  EXPECT_EQ(Sha256Hex(""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
  EXPECT_EQ(Sha256Hex("abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
}

TEST(ContentHashTest, CaseAndWhitespaceDoNotMatter) {
  EXPECT_EQ(ContentHash("[SYNTHETIC] Apple beats", "Revenue  rose 5%."),
            ContentHash("[SYNTHETIC] APPLE BEATS", "Revenue rose 5%.\n"));
}

TEST(ContentHashTest, OneWordChangesTheHash) {
  EXPECT_NE(ContentHash("Apple beats", "Revenue rose 5%."),
            ContentHash("Apple beats", "Revenue increased 5%."));
}

TEST(ContentHashTest, HeadlineAndBodyAreSeparated) {
  EXPECT_NE(ContentHash("a b", "c"), ContentHash("a", "b c"));
}

// Expected values computed independently with the legacy algorithm
// (SHA-256 of norm(headline) + "\n" + norm(body), in Python).
struct HashVector {
  std::string_view headline;
  std::string_view body;
  std::string_view hash;
};

constexpr std::array<HashVector, 7> kVectors = {{
    {"", "",
     "01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b"},
    {"Apple beats", "Revenue rose 5%.",
     "7a99556b25f9aa2d3bb3d033294b8e31ba35b67d38c6814c453936017cfabca8"},
    {"  [SYNTHETIC]  Apple\tREPORTS  ", "\n\nLine one.\r\n\f\vLine two.  ",
     "bafb9cc67f4f912577926531162b9c09c576b3b85382b05173ba9c948b3ce261"},
    {"Caf\xC3\xA9 \xC3\x89"
     "CLAIR",
     "\xC3\x9Cn\xC3\xAF"
     "c\xC3\xB6"
     "d\xC3\xA9 stays; only ASCII LOWERCASES",
     "23967c1ef26b880b55c9b5787f4b4fb0ca50d8643ebdc9e5b9fd2eb42950bf39"},
    {"a b", "c",
     "24b366cf6891c1a7ba83804c7632b71c9d86cf530908a052bf08d0e128602da8"},
    {"A\vB", "x\fY",
     "470795eb724d4f41fcaae6b6cd62ff6d938c8722458ec8526f33319ffda3023b"},
    {"[SYNTHETIC] Apple reports Q3 revenue of $85.1B, up 12% from a year ago",
     "Apple Inc. (AAPL) said revenue for its fiscal Q3 reached $85.1 billion, "
     "up 12% from a year earlier. Earnings per share were $1.40. Management "
     "will discuss the results on its scheduled conference call.\n\n"
     "Generated by premarket-ai vendor-sim. Not real news.",
     "e5f3a489e9a70b0d23ad4873144cf0adedde3bf6b22533580f929b48bdf8eacc"},
}};

TEST(ContentHashTest, MatchesLegacyVectors) {
  for (const HashVector& vector : kVectors) {
    EXPECT_EQ(ContentHash(vector.headline, vector.body), vector.hash)
        << "headline: " << vector.headline;
  }
}

TEST(ContentHasherTest, ReusedHasherMatchesOneShot) {
  absl::StatusOr<std::unique_ptr<ContentHasher>> hasher =
      ContentHasher::Create();
  ASSERT_TRUE(hasher.ok()) << hasher.status();
  std::array<char, kContentHashSize> out{};
  for (int round = 0; round < 3; ++round) {
    for (const HashVector& vector : kVectors) {
      ASSERT_TRUE((*hasher)->Hash(vector.headline, vector.body, out));
      EXPECT_EQ(std::string_view(out.data()), vector.hash);
      EXPECT_EQ(out[kContentHashSize - 1], '\0');
    }
  }
}

TEST(ContentHasherTest, TextLongerThanOneChunk) {
  // Crosses the 4 KiB chunk boundary many times, with whitespace runs
  // straddling it.
  std::string body;
  for (int i = 0; i < 2000; ++i) body += "Word  \t\nMORE ";
  const std::string headline(5000, 'H');
  EXPECT_EQ(ContentHash(headline, body),
            Sha256Hex(NormalizeText(headline) + "\n" + NormalizeText(body)));
}

}  // namespace
}  // namespace premarket::ingest
