// Copyright 2026 premarket-ai contributors
// SPDX-License-Identifier: MIT

#include "ingest/feed_parser.h"

#include <memory>
#include <string>
#include <utility>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "gtest/gtest.h"
#include "ingest/news_item.h"

namespace premarket::ingest {
namespace {

constexpr char kItem[] =
    "{\"id\":\"VND-20260924-001\",\"headline\":\"[SYNTHETIC] Apple beats\","
    "\"body\":\"Line one.\\n\\nGenerated by premarket-ai vendor-sim.\","
    "\"source_url\":\"https://wire.vendornews.example/a\","
    "\"source_domain\":\"wire.vendornews.example\","
    "\"published_at\":\"2026-09-24T09:05:00Z\","
    "\"tickers\":[\"AAPL\",\"MSFT\"],\"synthetic\":true}";

// Parses feeds and single items the way the ingester does.
class FeedParserTest : public ::testing::Test {
 protected:
  void SetUp() override {
    absl::StatusOr<std::unique_ptr<FeedParser>> parser =
        FeedParser::Create(1 << 16, 64);
    ASSERT_TRUE(parser.ok()) << parser.status();
    parser_ = *std::move(parser);
  }

  absl::Status ParseFeed(const std::string& feed) {
    if (!buffer_.Assign(feed)) return absl::ResourceExhaustedError("big");
    return parser_->Parse(buffer_);
  }

  // Legacy's ParseItem(item_json): the item wrapped in a one-item feed.
  absl::Status ParseItem(const std::string& item_json, NewsItem* item) {
    absl::Status status = ParseFeed("{\"items\":[" + item_json + "]}");
    if (!status.ok()) return status;
    if (parser_->item_count() != 1) return absl::InternalError("count");
    parser_->ExtractItem(0, item);
    return ItemErrorStatus(*item);
  }

  FeedBuffer buffer_{1 << 16};
  std::unique_ptr<FeedParser> parser_;
};

TEST_F(FeedParserTest, ParsesEveryField) {
  NewsItem item;
  const absl::Status status = ParseItem(kItem, &item);
  ASSERT_TRUE(status.ok()) << status;
  EXPECT_EQ(item.vendor_item_id, "VND-20260924-001");
  EXPECT_EQ(item.headline, "[SYNTHETIC] Apple beats");
  EXPECT_EQ(item.body, "Line one.\n\nGenerated by premarket-ai vendor-sim.");
  EXPECT_EQ(item.source_domain, "wire.vendornews.example");
  EXPECT_EQ(item.published_at, "2026-09-24T09:05:00Z");
  ASSERT_EQ(item.tickers().size(), 2u);
  EXPECT_EQ(item.tickers()[1], "MSFT");
  EXPECT_TRUE(item.synthetic);
  EXPECT_FALSE(item.is_dup);
}

TEST_F(FeedParserTest, SyntheticDefaultsToTrue) {
  std::string item_json = kItem;
  item_json.replace(item_json.find(",\"synthetic\":true"), 17, "");
  NewsItem item;
  ASSERT_TRUE(ParseItem(item_json, &item).ok());
  EXPECT_TRUE(item.synthetic);
  item_json = kItem;
  item_json.replace(item_json.find("true"), 4, "false");
  ASSERT_TRUE(ParseItem(item_json, &item).ok());
  EXPECT_FALSE(item.synthetic);
}

TEST_F(FeedParserTest, RejectsMissingField) {
  NewsItem item;
  const absl::Status status = ParseItem(
      "{\"id\":\"x\",\"headline\":\"h\",\"source_url\":\"u\","
      "\"source_domain\":\"d\",\"published_at\":\"p\",\"tickers\":[]}",
      &item);
  ASSERT_FALSE(status.ok());
  EXPECT_NE(status.message().find("body"), std::string::npos);
}

TEST_F(FeedParserTest, RejectsWrongTypes) {
  NewsItem item;
  EXPECT_FALSE(ParseItem("{\"id\":1}", &item).ok());
  EXPECT_FALSE(ParseItem("[1,2]", &item).ok());
  EXPECT_FALSE(ParseItem("not json", &item).ok());
  std::string bad_ticker = kItem;
  bad_ticker.replace(bad_ticker.find("\"MSFT\""), 6, "42");
  EXPECT_FALSE(ParseItem(bad_ticker, &item).ok());
  std::string bad_synthetic = kItem;
  bad_synthetic.replace(bad_synthetic.find("true"), 4, "\"yes\"");
  EXPECT_FALSE(ParseItem(bad_synthetic, &item).ok());
  std::string empty_id = kItem;
  empty_id.replace(empty_id.find("VND-20260924-001"), 16, "");
  EXPECT_FALSE(ParseItem(empty_id, &item).ok());
}

TEST_F(FeedParserTest, RejectsTooManyTickers) {
  std::string item_json = kItem;
  item_json.replace(item_json.find("[\"AAPL\",\"MSFT\"]"), 15,
                    "[\"A\",\"B\",\"C\",\"D\",\"E\",\"F\",\"G\",\"H\",\"I\"]");
  NewsItem item;
  const absl::Status status = ParseItem(item_json, &item);
  ASSERT_FALSE(status.ok());
  EXPECT_NE(status.message().find("tickers"), std::string::npos);
}

TEST_F(FeedParserTest, SplitsItemsInOrder) {
  const std::string feed = std::string("{\"feed_date\":\"2026-09-24\",") +
                           "\"items\":[" + kItem + "," + kItem + "]}";
  const absl::Status status = ParseFeed(feed);
  ASSERT_TRUE(status.ok()) << status;
  ASSERT_EQ(parser_->item_count(), 2u);
  NewsItem first;
  ASSERT_TRUE(parser_->ExtractItem(0, &first));
  EXPECT_EQ(first.headline, "[SYNTHETIC] Apple beats");
}

TEST_F(FeedParserTest, RejectsBadFeeds) {
  EXPECT_FALSE(ParseFeed("").ok());
  EXPECT_FALSE(ParseFeed("{\"items\":{}}").ok());
  EXPECT_FALSE(ParseFeed("{\"count\":0}").ok());
  EXPECT_TRUE(ParseFeed("{\"items\":[]}").ok());
  EXPECT_EQ(parser_->item_count(), 0u);
}

TEST_F(FeedParserTest, RejectsMoreThanMaxItems) {
  std::string feed = "{\"items\":[";
  for (int i = 0; i < 65; ++i) feed += (i == 0 ? "{}" : ",{}");
  feed += "]}";
  EXPECT_EQ(ParseFeed(feed).code(), absl::StatusCode::kResourceExhausted);
}

TEST(FeedBufferTest, RefusesToOverflow) {
  FeedBuffer buffer(8);
  EXPECT_TRUE(buffer.Append("1234", 4));
  EXPECT_TRUE(buffer.Append("5678", 4));
  EXPECT_FALSE(buffer.Append("9", 1));
  EXPECT_EQ(buffer.view(), "12345678");
  buffer.Clear();
  EXPECT_EQ(buffer.size(), 0u);
}

}  // namespace
}  // namespace premarket::ingest
