import {screen, waitFor, within} from '@testing-library/react';
import {HttpResponse, http} from 'msw';
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest';

import type {NewsDetailWire} from '@/api/schemas/news';
import {apiUrl} from '@/lib/env';
import {db} from '@/mocks/data/db';
import {server} from '@/mocks/node';
import {setScenario} from '@/mocks/scenarios';
import {expectNoA11yViolations} from '@/test/axe';
import {renderApp, withMockSession} from '@/test/render';

// Friday 2026-09-25, 09:00 in New York. Only Date is faked; timers are real.
const NOW = new Date('2026-09-25T13:00:00Z');
const TODAY = '2026-09-25';
const WAIT = {timeout: 10_000};

beforeEach(() => {
  vi.useFakeTimers({toFake: ['Date']});
  vi.setSystemTime(NOW);
  withMockSession();
});

afterEach(() => {
  vi.useRealTimers();
  server.events.removeAllListeners();
});

/** An item of today's mock feed matching `test`. */
function todayItem(test: (item: NewsDetailWire) => boolean): NewsDetailWire {
  const item = db.day(TODAY).items.find(test);
  if (item === undefined) {
    throw new Error('No such item in the mock feed');
  }
  return item;
}

const plainItem = () =>
  todayItem(
    item =>
      !item.is_dup &&
      item.source_url.startsWith('https://') &&
      item.tickers.length > 0,
  );

async function openItem(id: number) {
  const view = renderApp(`/news/${id}`);
  await screen.findByRole('article', {}, WAIT);
  return view;
}

describe('NewsDetailPage: content', () => {
  it('shows the item in full, with times in ET and UTC', async () => {
    const item = plainItem();
    const {container} = await openItem(item.id);

    expect(
      screen.getByRole('heading', {level: 1, name: item.headline}),
    ).toBeInTheDocument();
    expect(document.title).toBe(`${item.headline} · premarket-ai`);
    // Expected values built independently of the app's formatters.
    const published = new Date(item.published_at);
    const et = new Intl.DateTimeFormat('en-US', {
      timeZone: 'America/New_York',
      hour: '2-digit',
      minute: '2-digit',
      hourCycle: 'h23',
    }).format(published);
    const utc = `${item.published_at.slice(0, 10)} ${item.published_at.slice(11, 16)} UTC`;
    const time = screen.getByText(new RegExp(`, ${et} ET$`), {
      selector: 'time',
    });
    expect(time).toHaveAttribute('dateTime', item.published_at);
    expect(screen.getByText(`(${utc})`, {exact: false})).toBeInTheDocument();
    expect(
      screen.getByText('Generated by premarket-ai vendor-sim. Not real news.'),
    ).toBeInTheDocument();
    expect(screen.getByText(item.vendor_item_id)).toBeInTheDocument();
    expect(
      within(screen.getByRole('article')).getAllByText(
        'Friday, September 25, 2026',
      ).length,
    ).toBeGreaterThan(0);
    await expectNoA11yViolations(container);
  });

  it('links the source safely, showing the real host', async () => {
    const item = plainItem();
    await openItem(item.id);

    const link = screen.getByRole('link', {name: /opens in a new tab/});
    expect(link).toHaveAttribute('href', item.source_url);
    expect(link).toHaveAttribute('target', '_blank');
    expect(link).toHaveAttribute('rel', 'noopener noreferrer nofollow');
    expect(link).toHaveTextContent(new URL(item.source_url).hostname);
  });

  it('says so when the link leads to another site than the claimed source', async () => {
    const item = todayItem(
      entry =>
        entry.source_url.startsWith('https://') &&
        new URL(entry.source_url).hostname !== entry.source_domain,
    );
    await openItem(item.id);

    expect(
      screen.getByText('(the link opens a different site)'),
    ).toBeInTheDocument();
    expect(
      screen.getByRole('link', {name: /opens in a new tab/}),
    ).toHaveTextContent('pennyrocket.example');
    expect(screen.getByText(/^Source: reuters-news\.test/)).toBeInTheDocument();
  });

  it('never links a javascript: source', async () => {
    const item = todayItem(entry => entry.source_url.startsWith('javascript:'));
    const {container} = await openItem(item.id);

    expect(
      screen.getByText('(link not shown: not a web address)'),
    ).toBeInTheDocument();
    expect(container.querySelector('a[href^="javascript"]')).toBeNull();
  });

  it('renders HTML-looking vendor text as plain text', async () => {
    const item = todayItem(entry => entry.headline.includes('<script>'));
    await openItem(item.id);

    const article = screen.getByRole('article');
    expect(article.querySelector('script, img, b')).toBeNull();
    expect(
      within(article).getByText(/<img src=x onerror=/),
    ).toBeInTheDocument();
  });

  it('says which item a duplicate copies, and how it matched', async () => {
    const item = todayItem(entry => entry.dup_type === 'near');
    await openItem(item.id);

    expect(
      screen.getByText(`Yes, duplicate of ${item.dup_of ?? ''} (near copy)`),
    ).toBeInTheDocument();
    expect(screen.getByText('DUPLICATE · near')).toBeInTheDocument();
  });

  it("links each ticker to that day's feed filtered by it", async () => {
    const item = plainItem();
    await openItem(item.id);
    const [ticker] = item.tickers;

    expect(
      screen.getByRole('link', {name: `${ticker}: show its news in the feed`}),
    ).toHaveAttribute('href', `/news?date=${TODAY}&ticker=${ticker}`);
  });
});

describe('NewsDetailPage: rule checks', () => {
  function ruleSection(): HTMLElement {
    return screen.getByRole('region', {name: 'Rule checks'});
  }

  it('lists what the rules found, badge and message', async () => {
    const item = todayItem(
      entry =>
        entry.reason_codes.includes('SPOOFED_SOURCE') &&
        entry.reason_codes.includes('FAKE_TICKER'),
    );
    const {container} = await openItem(item.id);

    const section = ruleSection();
    for (const evidence of item.rule_evidence) {
      expect(within(section).getByText(evidence.message)).toBeInTheDocument();
    }
    expect(within(section).getAllByText('FAKE TICKER').length).toBeGreaterThan(
      0,
    );
    expect(within(section).getByText('SPOOFED SOURCE')).toBeInTheDocument();
    expect(
      within(section).queryByText('No rule flagged this item.'),
    ).not.toBeInTheDocument();
    // The same codes as badges under the headline.
    expect(
      within(screen.getByRole('list', {name: 'Rule checks'})).getByText(
        'SPOOFED SOURCE',
      ),
    ).toBeInTheDocument();
    await expectNoA11yViolations(container);
  });

  it('says so when no rule flagged the item', async () => {
    await openItem(
      todayItem(
        entry =>
          entry.reason_codes.length === 0 &&
          !entry.is_dup &&
          entry.copies === 0,
      ).id,
    );

    expect(
      within(ruleSection()).getByText('No rule flagged this item.'),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole('list', {name: 'Rule checks'}),
    ).not.toBeInTheDocument();
  });

  it('shows the copies of an original', async () => {
    const item = todayItem(entry => entry.copies > 0);
    await openItem(item.id);

    expect(screen.getByText('Copies of this story')).toBeInTheDocument();
    expect(screen.getByText(`DUPLICATE ×${item.copies}`)).toBeInTheDocument();
  });

  it("says so when the rules haven't run for the item", async () => {
    const item = db.day('2026-09-18').items[0];
    await openItem(item?.id ?? 0);

    expect(
      within(ruleSection()).getByText(
        "Rule checks haven't run for this item yet.",
      ),
    ).toBeInTheDocument();
  });

  it('renders evidence as text and unknown codes as neutral badges', async () => {
    const item = plainItem();
    server.use(
      http.get(apiUrl('/news/:id'), () =>
        HttpResponse.json({
          ...item,
          reason_codes: ['INJECTION_ATTEMPT'],
          rule_evidence: [
            {
              check: 'entity',
              code: 'INJECTION_ATTEMPT',
              message: 'Body says <img src=x onerror=alert(1)> to the model.',
            },
          ],
        }),
      ),
    );
    await openItem(item.id);

    const section = ruleSection();
    expect(
      within(section).getByText(
        'Body says <img src=x onerror=alert(1)> to the model.',
      ),
    ).toBeInTheDocument();
    expect(section.querySelector('img')).toBeNull();
    expect(within(section).getByText('INJECTION ATTEMPT')).toHaveAttribute(
      'data-variant',
      'outline',
    );
  });
});

describe('NewsDetailPage: back to the feed', () => {
  it('returns to the feed with its filters', async () => {
    const {user, router} = renderApp('/news?q=Zentrality');
    const list = await screen.findByRole('list', {name: 'News items'}, WAIT);
    const [first] = within(list).getAllByRole('link');

    await user.click(first ?? document.body);
    await screen.findByRole('article', {}, WAIT);
    const back = screen.getByRole('link', {name: 'Back to the feed'});
    expect(back).toHaveAttribute('href', `/news?date=${TODAY}&q=Zentrality`);
    // Focus moved to the page, not left on <body>.
    expect(document.activeElement).toBe(document.getElementById('main'));

    await user.click(back);
    expect(
      await screen.findByRole('list', {name: 'News items'}, WAIT),
    ).toBeInTheDocument();
    expect(router.state.location.search).toContain('q=Zentrality');
    expect(screen.getByLabelText('Search headlines and text')).toHaveValue(
      'Zentrality',
    );
  });

  it("opened directly, returns to the item's feed date", async () => {
    await openItem(plainItem().id);

    expect(
      screen.getByRole('link', {name: 'Back to the feed'}),
    ).toHaveAttribute('href', `/news?date=${TODAY}`);
  });
});

describe('NewsDetailPage: states', () => {
  it('404: says the item does not exist, with a way back', async () => {
    const {container} = renderApp('/news/999');

    expect(
      await screen.findByRole(
        'heading',
        {name: "This item doesn't exist"},
        WAIT,
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByRole('link', {name: 'Back to the feed'}),
    ).toHaveAttribute('href', '/news');
    await expectNoA11yViolations(container);
  });

  it('contract-drift: "Unexpected response from the server" and Retry', async () => {
    const consoleError = vi
      .spyOn(console, 'error')
      .mockImplementation(() => undefined);
    setScenario('contract-drift');
    renderApp(`/news/${plainItem().id}`);

    expect(
      await screen.findByText('Unexpected response from the server.', {}, WAIT),
    ).toBeInTheDocument();
    expect(screen.getByRole('button', {name: 'Retry'})).toBeInTheDocument();
    expect(
      screen.getByRole('heading', {level: 1, name: 'News item'}),
    ).toBeInTheDocument();
    consoleError.mockRestore();
  });

  it('a malformed id is "does not exist" without a request', async () => {
    let requests = 0;
    server.events.on('request:start', ({request}) => {
      if (new URL(request.url).pathname.startsWith('/api/news')) {
        requests += 1;
      }
    });
    renderApp('/news/abc');

    expect(
      await screen.findByRole(
        'heading',
        {name: "This item doesn't exist"},
        WAIT,
      ),
    ).toBeInTheDocument();
    expect(requests).toBe(0);
  });

  it('server-error: a plain message and a working Retry', async () => {
    setScenario('server-error');
    const {user, container} = renderApp(`/news/${plainItem().id}`);

    expect(
      await screen.findByText('The server had a problem. Try again.', {}, WAIT),
    ).toBeInTheDocument();
    expect(screen.getByText("Couldn't load this item")).toBeInTheDocument();
    await expectNoA11yViolations(container);
    setScenario('default');
    await user.click(screen.getByRole('button', {name: 'Retry'}));

    expect(await screen.findByRole('article', {}, WAIT)).toBeInTheDocument();
  });

  it('slow: a skeleton while loading', async () => {
    setScenario('slow');
    renderApp(`/news/${plainItem().id}`);

    expect(
      await screen.findByText('Loading the item…', {}, WAIT),
    ).toBeInTheDocument();
    expect(await screen.findByRole('article', {}, WAIT)).toBeInTheDocument();
  });

  it('running: an item that has not arrived yet does not exist', async () => {
    setScenario('running');
    // The newest item arrives last.
    renderApp(`/news/${db.day(TODAY).items[0]?.id ?? 0}`);

    expect(
      await screen.findByRole(
        'heading',
        {name: "This item doesn't exist"},
        WAIT,
      ),
    ).toBeInTheDocument();
  });
});

describe('NewsDetailPage: keyboard', () => {
  it('Enter on a feed row opens the item and puts focus on the page', async () => {
    const {user} = renderApp('/news');
    await screen.findByRole('list', {name: 'News items'}, WAIT);

    await user.keyboard('j');
    await user.keyboard('{Enter}');

    await screen.findByRole('article', {}, WAIT);
    await waitFor(() =>
      expect(document.activeElement).toBe(document.getElementById('main')),
    );
  });
});
