// Copyright 2026 premarket-ai contributors
// SPDX-License-Identifier: MIT
//
// Google Benchmark micro-benchmarks for the legacy hot paths. These numbers
// are the baseline the C++20 ingester (increment 2) is compared against.

#include <benchmark/benchmark.h>

#include <cstddef>
#include <string>
#include <thread>
#include <vector>

#include "ingest/bounded_queue.h"
#include "ingest/feed_parser.h"
#include "ingest/ingester.h"
#include "ingest/normalize.h"

namespace premarket {
namespace legacy {
namespace {

std::string ItemJson(int n) {
  return "{\"id\":\"VND-20260924-" + std::to_string(n) +
         "\",\"headline\":\"[SYNTHETIC] Apple reports Q3 revenue of $85.1B, "
         "up 12% from a year ago\",\"body\":\"Apple Inc. (AAPL) said revenue "
         "for its fiscal Q3 reached $85.1 billion, up 12% from a year "
         "earlier. Earnings per share were $1.40. Management will discuss "
         "the results on its scheduled conference call.\\n\\nGenerated by "
         "premarket-ai vendor-sim. Not real news.\",\"source_url\":\"https://"
         "wire.vendornews.example/2026/09/24/apple-" +
         std::to_string(n) +
         "\",\"source_domain\":\"wire.vendornews.example\",\"published_at\":"
         "\"2026-09-24T09:05:00Z\",\"tickers\":[\"AAPL\"],\"synthetic\":true}";
}

std::string FeedJson(int count) {
  std::string feed = "{\"feed_date\":\"2026-09-24\",\"items\":[";
  for (int i = 0; i < count; ++i) {
    if (i > 0) feed += ",";
    feed += ItemJson(i);
  }
  return feed + "]}";
}

void BM_ParseItem(benchmark::State& state) {
  const std::string json = ItemJson(1);
  for (auto _ : state) {
    StatusOr<NewsItem> item = ParseItem(json);
    benchmark::DoNotOptimize(item);
  }
}
BENCHMARK(BM_ParseItem);

void BM_ContentHash(benchmark::State& state) {
  StatusOr<NewsItem> item = ParseItem(ItemJson(1));
  for (auto _ : state) {
    std::string hash = ContentHash(item.value().headline, item.value().body);
    benchmark::DoNotOptimize(hash);
  }
}
BENCHMARK(BM_ContentHash);

void BM_QueuePingPong(benchmark::State& state) {
  BoundedQueue<int> queue(64);
  for (auto _ : state) {
    queue.Push(1);
    int value = 0;
    queue.Pop(&value);
    benchmark::DoNotOptimize(value);
  }
}
BENCHMARK(BM_QueuePingPong);

void BM_QueueProducerConsumer(benchmark::State& state) {
  const int kItems = 10000;
  for (auto _ : state) {
    BoundedQueue<int> queue(64);
    std::thread consumer([&queue]() {
      int value = 0;
      while (queue.Pop(&value)) benchmark::DoNotOptimize(value);
    });
    for (int i = 0; i < kItems; ++i) queue.Push(i);
    queue.Close();
    consumer.join();
  }
  state.SetItemsProcessed(state.iterations() * kItems);
}
BENCHMARK(BM_QueueProducerConsumer)->UseRealTime();

// A whole 100-item feed through the thread pool, by worker count.
void BM_ProcessFeed(benchmark::State& state) {
  const std::string feed = FeedJson(100);
  const int workers = static_cast<int>(state.range(0));
  for (auto _ : state) {
    StatusOr<std::vector<NewsItem>> items =
        ProcessFeed(feed, workers, 64, nullptr);
    benchmark::DoNotOptimize(items);
  }
  state.SetItemsProcessed(state.iterations() * 100);
}
BENCHMARK(BM_ProcessFeed)->Arg(1)->Arg(2)->Arg(4)->Arg(8)->UseRealTime();

}  // namespace
}  // namespace legacy
}  // namespace premarket

BENCHMARK_MAIN();
