// Copyright 2026 premarket-ai contributors
// SPDX-License-Identifier: MIT
//
// Google Benchmark micro-benchmarks for the C++20 hot paths. Same inputs
// and names as cpp/legacy/bench/legacy_bench.cc, so legacy_bench and
// ingest_bench numbers compare directly.

#include <benchmark/benchmark.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <span>
#include <string>
#include <thread>
#include <utility>

#include "absl/status/statusor.h"
#include "ingest/content_hash.h"
#include "ingest/feed_parser.h"
#include "ingest/ingester.h"
#include "ingest/mpmc_queue.h"
#include "ingest/news_item.h"

namespace premarket::ingest {
namespace {

std::string ItemJson(int n) {
  return "{\"id\":\"VND-20260924-" + std::to_string(n) +
         "\",\"headline\":\"[SYNTHETIC] Apple reports Q3 revenue of $85.1B, "
         "up 12% from a year ago\",\"body\":\"Apple Inc. (AAPL) said revenue "
         "for its fiscal Q3 reached $85.1 billion, up 12% from a year "
         "earlier. Earnings per share were $1.40. Management will discuss "
         "the results on its scheduled conference call.\\n\\nGenerated by "
         "premarket-ai vendor-sim. Not real news.\",\"source_url\":\"https://"
         "wire.vendornews.example/2026/09/24/apple-" +
         std::to_string(n) +
         "\",\"source_domain\":\"wire.vendornews.example\",\"published_at\":"
         "\"2026-09-24T09:05:00Z\",\"tickers\":[\"AAPL\"],\"synthetic\":true}";
}

std::string FeedJson(int count) {
  std::string feed = "{\"feed_date\":\"2026-09-24\",\"items\":[";
  for (int i = 0; i < count; ++i) {
    if (i > 0) feed += ",";
    feed += ItemJson(i);
  }
  return feed + "]}";
}

// Legacy parses one re-serialized item with RapidJSON. Here: simdjson
// parses the one-item feed, then the fields are extracted as views.
void BM_ParseItem(benchmark::State& state) {
  const std::string json = "{\"items\":[" + ItemJson(1) + "]}";
  FeedBuffer buffer(json.size());
  buffer.Assign(json);
  std::unique_ptr<FeedParser> parser = *FeedParser::Create(json.size(), 1);
  NewsItem item;
  for (auto _ : state) {
    bool ok = parser->Parse(buffer).ok() && parser->ExtractItem(0, &item);
    benchmark::DoNotOptimize(ok);
    benchmark::DoNotOptimize(item);
  }
}
BENCHMARK(BM_ParseItem);

// Field extraction alone, on an already parsed document (the per-item work
// a worker does).
void BM_ExtractItem(benchmark::State& state) {
  const std::string json = "{\"items\":[" + ItemJson(1) + "]}";
  FeedBuffer buffer(json.size());
  buffer.Assign(json);
  std::unique_ptr<FeedParser> parser = *FeedParser::Create(json.size(), 1);
  bool parsed = parser->Parse(buffer).ok();
  benchmark::DoNotOptimize(parsed);
  NewsItem item;
  for (auto _ : state) {
    benchmark::DoNotOptimize(parser->ExtractItem(0, &item));
    benchmark::DoNotOptimize(item);
  }
}
BENCHMARK(BM_ExtractItem);

void BM_ContentHash(benchmark::State& state) {
  const std::string json = "{\"items\":[" + ItemJson(1) + "]}";
  FeedBuffer buffer(json.size());
  buffer.Assign(json);
  std::unique_ptr<FeedParser> parser = *FeedParser::Create(json.size(), 1);
  NewsItem item;
  bool ok = parser->Parse(buffer).ok() && parser->ExtractItem(0, &item);
  benchmark::DoNotOptimize(ok);
  std::unique_ptr<ContentHasher> hasher = *ContentHasher::Create();
  std::array<char, kContentHashSize> out{};
  for (auto _ : state) {
    benchmark::DoNotOptimize(hasher->Hash(item.headline, item.body, out));
    benchmark::DoNotOptimize(out);
  }
}
BENCHMARK(BM_ContentHash);

void BM_QueuePingPong(benchmark::State& state) {
  MpmcQueue<int> queue(64);
  for (auto _ : state) {
    queue.TryPush(1);
    int value = 0;
    queue.TryPop(&value);
    benchmark::DoNotOptimize(value);
  }
}
BENCHMARK(BM_QueuePingPong);

void BM_QueueProducerConsumer(benchmark::State& state) {
  constexpr int kItems = 10000;
  for (auto _ : state) {
    MpmcQueue<int> queue(64);
    std::thread consumer([&queue]() {
      int value = 0;
      for (int received = 0; received < kItems;) {
        if (queue.TryPop(&value)) {
          benchmark::DoNotOptimize(value);
          ++received;
        }
      }
    });
    for (int i = 0; i < kItems; ++i) {
      while (!queue.TryPush(i)) {
      }
    }
    consumer.join();
  }
  state.SetItemsProcessed(state.iterations() * kItems);
}
BENCHMARK(BM_QueueProducerConsumer)->UseRealTime();

// A whole 100-item feed through the worker pool, by worker count. The pool
// and buffers are created once (as in production); legacy creates its
// thread pool per call, because that is how it runs.
void BM_ProcessFeed(benchmark::State& state) {
  const std::string feed = FeedJson(100);
  std::unique_ptr<FeedProcessor> processor =
      *FeedProcessor::Create({.workers = static_cast<int>(state.range(0)),
                              .queue_capacity = 64,
                              .max_items = 4096,
                              .max_feed_bytes = std::size_t{1} << 20});
  for (auto _ : state) {
    absl::StatusOr<std::span<NewsItem>> items = processor->ProcessFeed(feed);
    benchmark::DoNotOptimize(items);
  }
  state.SetItemsProcessed(state.iterations() * 100);
}
BENCHMARK(BM_ProcessFeed)->Arg(1)->Arg(2)->Arg(4)->Arg(8)->UseRealTime();

}  // namespace
}  // namespace premarket::ingest

BENCHMARK_MAIN();
